### ISSUE TITLE
txt2img

### ISSUE THREAD

**Issue by lepriko** [thygate/stable-diffusion-webui-depthmap-script#249] opened 2023-06-07 09:25 UTC
Hello, I would be really happy if someone can tell me what I'm missing. 
So If I go to the txt2img tab in automatic-1111 and generate an image using Controlnet depth with "preprocessor: depth_zoe, model: control_v11f1p_sd15_depth everything is working great. Even if I take the depth image generated by it and try to generate again using the only model: control_v11f1p_sd15_depth without preprocessor everything is working as expected. But, if I try to generate a depth map using this extension (no matter the model, I tried with every possible)  and then take the depth map output to txt2img controlNet with  model: control_v11f1p_sd15_depth no preprocessor. It is just not working. It generates random images nothing like the depth map. So I'm sure, I'm missing something. Can depth maps generated using this extension can be used in controlNet with control_v11f1p_sd15_depth model or should I download another model or it's impossible? I'm confused. :)  So, please can someone shed some light on the topic?

**Comment by lepriko** [comment] 2023-06-08 05:19
Could you please, tell me how to check this? I can't find it in the settings. The other strange thing is that if I put the depth mask and hit preview, the preview goes black white page. And if I put the working depth mask generated from the preprocessor it comes alright on preview.

**Comment by thygate** [comment] 2023-06-08 09:46
On windows, right click, properties, details tab : bit depth.. For other platforms use something imagemagick's identify command..

What file type / bitdepth does the controlnet depth preview create ?

**Comment by lepriko** [comment] 2023-06-08 15:14
Well, it says 16, it must be something else.

**Comment by lepriko** [comment] 2023-06-09 05:39
Thank you, I will try that but the strange thing is that from today I got out of memory error using 24GB VRAM card. Dunno what is going on :/

**Comment by lepriko** [comment] 2023-06-09 05:50
Just tested your approach and it is working. Thank you so much for this :) What I'm thinking is there is a way to save the generated images as 8-bit directly from the script? I'm gonna check the code, any help there will be appreciated. :)

**Comment by thygate** [comment] 2023-06-09 13:02
If you save as jpeg it will always be rgb with 8 bits per channel since it doesn't support single channel images.

I would not recommend using 8 bit depth maps.
Using an 8 bit depth map to generate the inpainted mesh for instance will result in banding due to the low dynamic range..

I assume controlnet is just always dividing by 256 instead of looking at the actual bit depth when loading a depthmap, so the issue is really over there imho.

**Comment by semjon00** [comment] 2023-07-19 11:24
Won't fix, also see #291

**Closed by semjon00** 2023-07-19 11:24 UTC
