### ISSUE TITLE
RuntimeError: Could not import backend "EGL": Could not initialize

### ISSUE THREAD

**Issue by angeldart** [thygate/stable-diffusion-webui-depthmap-script#161] opened 2023-04-07 05:56 UTC
When trying to generate the video with the ply file trowns that error, in running it in Google colab with fast_stable diffusion. Loading mesh ..
Error completing request
Arguments: ('outputs/extras-images/depthmap-0000.ply', '300', '40', 2, '-0.015, 0.0, -0.05', '0.03, 0.03, 0.05, 0.03', True, 0, 2) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 851, in run_makevideo
    fn_saved = run_3dphoto_videos(fn_mesh, basename, outpath, num_frames, num_fps, crop_border, vid_traj, x_shift_range, y_shift_range, z_shift_range, [''], dolly, fnExt, vid_ssaa)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 739, in run_3dphoto_videos
    vispy.use(app='egl')
  File "/usr/local/lib/python3.9/dist-packages/vispy/util/wrappers.py", line 93, in use
    use_app(app)
  File "/usr/local/lib/python3.9/dist-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/usr/local/lib/python3.9/dist-packages/vispy/app/application.py", line 47, in __init__
    self._use(backend_name)
  File "/usr/local/lib/python3.9/dist-packages/vispy/app/application.py", line 240, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "EGL":
Could not initialize

Loading mesh ..
Error completing request
Arguments: ('outputs/extras-images/depthmap-0000.ply', '300', '40', 2, '-0.015, 0.0, -0.05', '0.03, 0.03, 0.05, 0.03', True, 0, 2) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 851, in run_makevideo
    fn_saved = run_3dphoto_videos(fn_mesh, basename, outpath, num_frames, num_fps, crop_border, vid_traj, x_shift_range, y_shift_range, z_shift_range, [''], dolly, fnExt, vid_ssaa)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 739, in run_3dphoto_videos
    vispy.use(app='egl')
  File "/usr/local/lib/python3.9/dist-packages/vispy/util/wrappers.py", line 93, in use
    use_app(app)
  File "/usr/local/lib/python3.9/dist-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/usr/local/lib/python3.9/dist-packages/vispy/app/application.py", line 47, in __init__
    self._use(backend_name)
  File "/usr/local/lib/python3.9/dist-packages/vispy/app/application.py", line 240, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "EGL":
Could not initialize

[Colab paid products ](https://colab.research.google.com/signup?utm_source=footer&utm_medium=link&utm_campaign=footer_links)- [Cancel contracts here](https://colab.research.google.com/cancel-subscription)
arrow_right
Executing (23m 11s)  
<cell line: 61>
navigate_next
system()
navigate_next
_system_compat()
navigate_next
_run_command()
navigate_next
_monitor_process()
navigate_next
_poll_process()
Loading...

**Comment by thygate** [comment] 2023-04-08 16:00
duplicate of issue https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/163

**Closed by thygate** 2023-04-08 16:00 UTC
